In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [42]:
# Load datasets
customers = pd.read_csv("olist_customers_dataset.csv")
orders = pd.read_csv("olist_orders_dataset.csv")
order_items = pd.read_csv("olist_order_items_dataset.csv")
payments = pd.read_csv("olist_order_payments_dataset.csv")
reviews = pd.read_csv("olist_order_reviews_dataset.csv")
products = pd.read_csv("olist_products_dataset.csv")
sellers = pd.read_csv("olist_sellers_dataset.csv")
geolocation = pd.read_csv("olist_geolocation_dataset.csv")
category_translation = pd.read_csv("product_category_name_translation.csv")

In [43]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

summary = []

for name, df in datasets.items():
    summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicate Rows": df.duplicated().sum(),
        "Total Missing Values": df.isnull().sum().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

,Dataset,Rows,Columns,Duplicate Rows,Total Missing Values
0,customers,99441,5,0,0
1,orders,99441,8,0,4908
2,order_items,112650,7,0,0
3,payments,103886,5,0,0
4,reviews,99224,7,0,145903
5,products,32951,9,0,2448
6,sellers,3095,4,0,0
7,geolocation,1000163,5,261831,0
8,category_translation,71,2,0,0

In [44]:
def profile_dataset(df, name):
    print("=" * 60)
    print(f"DATASET: {name}")
    print("=" * 60)

    print(f"\nRows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]}")

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nData Types:")
    print(df.dtypes)

    print("\nSample Records:")
    print(df.head())

    print("\n")

In [45]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

for name, df in datasets.items():
    profile_dataset(df, name)

============================================================
DATASET: customers
============================================================

Rows: 99,441
Columns: 5

Column Names:
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Duplicate Rows:
0

Data Types:
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

Sample Records:
                        customer_id                customer_unique_id  \
0  06b8999e2fba1a1fbc88172c00ba8bc7  861eff4711a542e4b93843c6dd7febb0
1  18955e83d337fd6b2def6b18a428ac77  290c77bc529b7ac935b93aa66c333dc3
2  4e7b3e00288586ebd08712fdd0374a03  060e732b5b29e8181a18229c7b0b2b5e
3  b2b6027bc5c5109e529d4dc6358b12c3  259dac757896d24d7702b9acbbff3f3c
4  4f2d8ab171c80ec8364f7c12e35b23ad  345ecd01c38d18a9036ed96c73b8d066

   customer_zip_code_prefix          customer_city customer_state
0                     14409                 franca             SP
1                      9790  sao bernardo do campo             SP
2                      1151              sao paulo             SP
3                      8775        mogi das cruzes             SP
4                     13056               campinas             SP


============================================================
DATASET: orders
============================================================

Rows: 99,441
Columns: 8

Column Names:
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

Missing Values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Duplicate Rows:
0

Data Types:
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

Sample Records:
                           order_id                       customer_id  \
0  e481f51cbdc54678b7cc49136f2d6af7  9ef432eb6251297304e76186b10a928d
1  53cdb2fc8bc7dce0b6741e2150273451  b0830fb4747a6c6d20dea0b8c802d7ef
2  47770eb9100c2d0c44946d9cf07ec65d  41ce2a54c0b03bf3443c3d931a367089
3  949d5b44dbf5de918fe9c16f97b45f8a  f88197465ea7920adcdbec7375364d82
4  ad21c59c0840e6cb83a9ceb5573f8159  8ab97904e6daea8866dbdbc4fb7aad2c

  order_status order_purchase_timestamp    order_approved_at  \
0    delivered      2017-10-02 10:56:33  2017-10-02 11:07:15
1    delivered      2018-07-24 20:41:37  2018-07-26 03:24:27
2    delivered      2018-08-08 08:38:49  2018-08-08 08:55:23
3    delivered      2017-11-18 19:28:06  2017-11-18 19:45:59
4    delivered      2018-02-13 21:18:39  2018-02-13 22:20:29

  order_delivered_carrier_date order_delivered_customer_date  \
0          2017-10-04 19:55:00           2017-10-10 21:25:13
1          2018-07-26 14:31:00           2018-08-07 15:27:45
2          2018-08-08 13:50:00           2018-08-17 18:06:29
3          2017-11-22 13:39:59           2017-12-02 00:28:42
4          2018-02-14 19:46:34           2018-02-16 18:17:02

  order_estimated_delivery_date
0           2017-10-18 00:00:00
1           2018-08-13 00:00:00
2           2018-09-04 00:00:00
3           2017-12-15 00:00:00
4           2018-02-26 00:00:00


============================================================
DATASET: order_items
============================================================

Rows: 112,650
Columns: 7

Column Names:
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

Missing Values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Duplicate Rows:
0

Data Types:
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

Sample Records:
                           order_id  order_item_id  \
0  00010242fe8c5a6d1ba2dd792cb16214              1
1  00018f77f2f0320c557190d7a144bdd3              1
2  000229ec398224ef6ca0657da4fc703e              1
3  00024acbcdf0a6daa1e931b038114c75              1
4  00042b26cf59d7ce69dfabb4e55b4fd9              1

                         product_id                         seller_id  \
0  4244733e06e7ecb4970a6e2683c13e61  48436dade18ac8b2bce089ec2a041202
1  e5f2d52b802189ee658865ca93d83a8f  dd7ddc04e1b6c2c614352b383efe2d36
2  c777355d18b72b67abbeef9df44fd0fd  5b51032eddd242adc84c38acab88f23d
3  7634da152a4610f1595efa32f14722fc  9d7a1d34a5052409006425275ba1c2b4
4  ac6c3623068f30de03045865e4e10089  df560393f3a51e74553ab94004ba5c87

   shipping_limit_date   price  freight_value
0  2017-09-19 09:45:35   58.90          13.29
1  2017-05-03 11:05:13  239.90          19.93
2  2018-01-18 14:48:30  199.00          17.87
3  2018-08-15 10:10:18   12.99          12.79
4  2017-02-13 13:57:51  199.90          18.14


============================================================
DATASET: payments
============================================================

Rows: 103,886
Columns: 5

Column Names:
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

Missing Values:
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64

Duplicate Rows:
0

Data Types:
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

Sample Records:
                           order_id  payment_sequential payment_type  \
0  b81ef226f3fe1789b1e8b2acac839d17                   1  credit_card
1  a9810da82917af2d9aefd1278f1dcfa0                   1  credit_card
2  25e8ea4e93396b6fa0d3dd708e76c1bd                   1  credit_card
3  ba78997921bbcdc1373bb41e913ab953                   1  credit_card
4  42fdf880ba16b47b59251dd489d4441a                   1  credit_card

   payment_installments  payment_value
0                     8          99.33
1                     1          24.39
2                     1          65.71
3                     8         107.78
4                     2         128.45


============================================================
DATASET: reviews
============================================================

Rows: 99,224
Columns: 7

Column Names:
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

Missing Values:
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64

Duplicate Rows:
0

Data Types:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

Sample Records:
                          review_id                          order_id  \
0  7bc2406110b926393aa56f80a40eba40  73fc7af87114b39712e6da79b0a377eb
1  80e641a11e56f04c1ad469d5645fdfde  a548910a1c6147796b98fdf73dbeba33
2  228ce5500dc1d8e020d8d1322874b6f0  f9e4b658b201a9f2ecdecbb34bed034b
3  e64fb393e7b32834bb789ff8bb30750e  658677c97b385a9be170737859d3511b
4  f7c4243c7fe1938f181bec41a392bdeb  8e6bfb81e283fa7e4f11123a3fb894f1

   review_score review_comment_title  \
0             4                  NaN
1             5                  NaN
2             5                  NaN
3             5                  NaN
4             5                  NaN

                              review_comment_message review_creation_date  \
0                                                NaN  2018-01-18 00:00:00
1                                                NaN  2018-03-10 00:00:00
2                                                NaN  2018-02-17 00:00:00
3              Recebi bem antes do prazo estipulado.  2017-04-21 00:00:00
4  Parabéns lojas lannister adorei comprar pela I...  2018-03-01 00:00:00

  review_answer_timestamp
0     2018-01-18 21:46:59
1     2018-03-11 03:05:13
2     2018-02-18 14:36:24
3     2017-04-21 22:02:06
4     2018-03-02 10:26:53


============================================================
DATASET: products
============================================================

Rows: 32,951
Columns: 9

Column Names:
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

Missing Values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicate Rows:
0

Data Types:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

Sample Records:
                         product_id  product_category_name  \
0  1e9e8ef04dbcff4541ed26657ea517e5             perfumaria
1  3aa071139cb16b67ca9e5dea641aaa2f                  artes
2  96bd76ec8810374ed1b65e291975717f          esporte_lazer
3  cef67bcfe19066a932b7673e239eb23d                  bebes
4  9dc1a7de274444849c219cff195d0b71  utilidades_domesticas

   product_name_lenght  product_description_lenght  product_photos_qty  \
0                 40.0                       287.0                 1.0
1                 44.0                       276.0                 1.0
2                 46.0                       250.0                 1.0
3                 27.0                       261.0                 1.0
4                 37.0                       402.0                 4.0

   product_weight_g  product_length_cm  product_height_cm  product_width_cm
0             225.0               16.0               10.0              14.0
1            1000.0               30.0               18.0              20.0
2             154.0               18.0                9.0              15.0
3             371.0               26.0                4.0              26.0
4             625.0               20.0               17.0              13.0


============================================================
DATASET: sellers
============================================================

Rows: 3,095
Columns: 4

Column Names:
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

Missing Values:
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64

Duplicate Rows:
0

Data Types:
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

Sample Records:
                          seller_id  seller_zip_code_prefix  \
0  3442f8959a84dea7ee197c632cb2df15                   13023
1  d1b65fc7debc3361ea86b5f14c68d2e2                   13844
2  ce3ad9de960102d0677a81f5d0bb7b2d                   20031
3  c0f3eea2e14555b6faeea3dd58c1b1c3                    4195
4  51a04a8a6bdcb23deccc82b0b80742cf                   12914

         seller_city seller_state
0           campinas           SP
1         mogi guacu           SP
2     rio de janeiro           RJ
3          sao paulo           SP
4  braganca paulista           SP


============================================================
DATASET: geolocation
============================================================

Rows: 1,000,163
Columns: 5

Column Names:
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

Missing Values:
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64

Duplicate Rows:
261831

Data Types:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

Sample Records:
   geolocation_zip_code_prefix  geolocation_lat  geolocation_lng  \
0                         1037       -23.545621       -46.639292
1                         1046       -23.546081       -46.644820
2                         1046       -23.546129       -46.642951
3                         1041       -23.544392       -46.639499
4                         1035       -23.541578       -46.641607

  geolocation_city geolocation_state
0        sao paulo                SP
1        sao paulo                SP
2        sao paulo                SP
3        sao paulo                SP
4        sao paulo                SP


============================================================
DATASET: category_translation
============================================================

Rows: 71
Columns: 2

Column Names:
['product_category_name', 'product_category_name_english']

Missing Values:
product_category_name            0
product_category_name_english    0
dtype: int64

Duplicate Rows:
0

Data Types:
product_category_name            str
product_category_name_english    str
dtype: object

Sample Records:
    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [46]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "products": products,
    "sellers": sellers,
    "geolocation": geolocation,
    "category_translation": category_translation
}

summary = []

for name, df in datasets.items():
    summary.append({
        "Dataset": name,
        "Rows": df.shape[0],
        "Columns": df.shape[1],
        "Duplicate Rows": df.duplicated().sum(),
        "Total Missing Values": df.isnull().sum().sum()
    })

summary_df = pd.DataFrame(summary)

summary_df

,Dataset,Rows,Columns,Duplicate Rows,Total Missing Values
0,customers,99441,5,0,0
1,orders,99441,8,0,4908
2,order_items,112650,7,0,0
3,payments,103886,5,0,0
4,reviews,99224,7,0,145903
5,products,32951,9,0,2448
6,sellers,3095,4,0,0
7,geolocation,1000163,5,261831,0
8,category_translation,71,2,0,0

In [47]:
customers["customer_id"].nunique()

99441

In [48]:
len(customers)

99441

In [49]:
orders["order_id"].nunique()

99441

In [50]:
len(orders)

99441

In [51]:
products["product_id"].nunique()

32951

In [52]:
len(products)

32951

In [53]:
sellers["seller_id"].nunique()

3095

In [54]:
len(sellers)

3095

In [55]:
reviews["review_id"].nunique()

98410

In [56]:
len(reviews)

99224

In [57]:
reviews[reviews["review_id"].duplicated(keep=False)] \
[['review_id','order_id']] \
.sort_values('review_id') \
.head(20)

                              review_id                          order_id
46678  00130cbe1f9d422698c812ed8ded1919  dfcdfc43867d1c1381bfaf62d6b9c195
29841  00130cbe1f9d422698c812ed8ded1919  04a28263e085d399c97ae49e0b477efa
90677  0115633a9c298b6a98bcbe4eee75345f  78a4201f58af3463bdab842eea4bc801
63193  0115633a9c298b6a98bcbe4eee75345f  0c9850b2c179c1ef60d2855e2751d1fa
92876  0174caf0ee5964646040cd94e15ac95e  f93a732712407c02dce5dd5088d0f47b
57280  0174caf0ee5964646040cd94e15ac95e  74db91e33b4e1fd865356c89a61abf1f
54832  017808d29fd1f942d97e50184dfb4c13  8daaa9e99d60fbba579cc1c3e3bfae01
99167  017808d29fd1f942d97e50184dfb4c13  b1461c8882153b5fe68307c46a506e39
20621  0254bd905dc677a6078990aad3331a36  5bf226cf882c5bf4247f89a97c86f273
96080  0254bd905dc677a6078990aad3331a36  331b367bdd766f3d1cf518777317b5d9
89712  0288d42bef3dfe36930740c9588a570f  33d8795f04dd631f3480d7aaf90da3dc
94851  0288d42bef3dfe36930740c9588a570f  f889a5a0b44adc29c5465b99395ac3c1
47495  02aa7f5f75e964e3c7efa59a1f515281  d8e17d5f7dacf0970d316e7c03e741e8
95860  02aa7f5f75e964e3c7efa59a1f515281  db92613c074f00e53066388d48ad7512
71165  034528cb00b6bc981847acafbdf2ae0b  e1e8e3bca903de27e9a1c72b5a5795e0
81094  034528cb00b6bc981847acafbdf2ae0b  3d3742a96f24a8fe4e2e57628807e476
1988   03a6a25db577d0689440933055111897  2acfdc5131ff2cf4433e668454c9784c
9013   03a6a25db577d0689440933055111897  3fde8b7313af6b37b84b5c7594d7add0
21587  0467560f511c516ddaa54a60edb0c291  0c995611a99f81268d859184a416f1db
24901  0467560f511c516ddaa54a60edb0c291  55b2e390d5d80ada31ad1b795ebeb087

### Customers Table - Key Observations

* The customers dataset contains 99,441 records and 5 columns.
* No missing values or duplicate rows were identified.
* customer_id appears suitable as the primary business key.
* Customer location information is available at city and state level, enabling future geographic analysis.
* Overall, the dataset is clean and requires no preprocessing.

### Orders Table - Key Observations

* The orders dataset contains 99,441 records and captures the complete order lifecycle.
* Missing values exist in approval and delivery-related timestamps.
* These missing timestamps likely correspond to cancelled, unavailable, or undelivered orders rather than data quality issues.
* No duplicate records were found.
* The table will be critical for delivery performance and order fulfillment analysis.

### Remaining Tables - Key Observations

**Order Items**

* Contains 112,650 records with no missing values or duplicates.
* Represents product-level transactions and is a strong candidate for the fact table grain.

**Payments**

* Contains 103,886 payment records with complete data quality.
* Supports payment behavior and installment analysis.

**Reviews**

* Review scores are complete, but review titles and comments contain substantial missing values.
* Missing comments are expected because textual feedback is optional.
* review_id should not automatically be assumed to be unique and requires validation.

**Products**

* Most product records are complete.
* 610 products are missing category-related metadata and 2 products have missing dimensions.
* Missing values affect only a small proportion of records.

**Sellers**

* Clean dataset with no missing values or duplicates.
* Suitable for seller-level performance analysis.

**Geolocation**

* Contains over 1 million records.
* Significant duplicate records (261,831) were detected.
* May require deduplication before use and is lower priority for initial modeling.

**Category Translation**

* Small lookup table with complete data quality.
* Can be merged with product information during transformation.

In [60]:


mql = pd.read_csv("olist_marketing_qualified_leads_dataset.csv")
closed_deals = pd.read_csv("olist_closed_deals_dataset.csv")

marketing_datasets = {
    "marketing_qualified_leads": mql,
    "closed_deals": closed_deals
}

for name, df in marketing_datasets.items():
    
    print("="*60)
    print(f"DATASET: {name}")
    print("="*60)

    print(f"\nRows: {df.shape[0]:,}")
    print(f"Columns: {df.shape[1]}")

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nDuplicate Rows:")
    print(df.duplicated().sum())

    print("\nData Types:")
    print(df.dtypes)

    print("\nSample Records:")
    print(df.head())

    print("\n")

============================================================
DATASET: marketing_qualified_leads
============================================================

Rows: 8,000
Columns: 4

Column Names:
['mql_id', 'first_contact_date', 'landing_page_id', 'origin']

Missing Values:
mql_id                 0
first_contact_date     0
landing_page_id        0
origin                60
dtype: int64

Duplicate Rows:
0

Data Types:
mql_id                str
first_contact_date    str
landing_page_id       str
origin                str
dtype: object

Sample Records:
                             mql_id first_contact_date  \
0  dac32acd4db4c29c230538b72f8dd87d         2018-02-01
1  8c18d1de7f67e60dbd64e3c07d7e9d5d         2017-10-20
2  b4bc852d233dfefc5131f593b538befa         2018-03-22
3  6be030b81c75970747525b843c1ef4f8         2018-01-22
4  5420aad7fec3549a85876ba1c529bd84         2018-02-21

                    landing_page_id          origin
0  88740e65d5d6b056e0cda098e1ea6313          social
1  007f9098284a86ee80ddeb25d53e0af8     paid_search
2  a7982125ff7aa3b2054c6e44f9d28522  organic_search
3  d45d558f0daeecf3cccdffe3c59684aa           email
4  b48ec5f3b04e9068441002a19df93c6c  organic_search


============================================================
DATASET: closed_deals
============================================================

Rows: 842
Columns: 14

Column Names:
['mql_id', 'seller_id', 'sdr_id', 'sr_id', 'won_date', 'business_segment', 'lead_type', 'lead_behaviour_profile', 'has_company', 'has_gtin', 'average_stock', 'business_type', 'declared_product_catalog_size', 'declared_monthly_revenue']

Missing Values:
mql_id                             0
seller_id                          0
sdr_id                             0
sr_id                              0
won_date                           0
business_segment                   1
lead_type                          6
lead_behaviour_profile           177
has_company                      779
has_gtin                         778
average_stock                    776
business_type                     10
declared_product_catalog_size    773
declared_monthly_revenue           0
dtype: int64

Duplicate Rows:
0

Data Types:
mql_id                               str
seller_id                            str
sdr_id                               str
sr_id                                str
won_date                             str
business_segment                     str
lead_type                            str
lead_behaviour_profile               str
has_company                       object
has_gtin                          object
average_stock                        str
business_type                        str
declared_product_catalog_size    float64
declared_monthly_revenue         float64
dtype: object

Sample Records:
                             mql_id                         seller_id  \
0  5420aad7fec3549a85876ba1c529bd84  2c43fb513632d29b3b58df74816f1b06
1  a555fb36b9368110ede0f043dfc3b9a0  bbb7d7893a450660432ea6652310ebb7
2  327174d3648a2d047e8940d7d15204ca  612170e34b97004b3ba37eae81836b4c
3  f5fee8f7da74f4887f5bcae2bafb6dd6  21e1781e36faf92725dde4730a88ca0f
4  ffe640179b554e295c167a2f6be528e0  ed8cb7b190ceb6067227478e48cf8dde

                             sdr_id                             sr_id  \
0  a8387c01a09e99ce014107505b92388c  4ef15afb4b2723d8f3d81e51ec7afefe
1  09285259593c61296eef10c734121d5b  d3d1e91a157ea7f90548eef82f1955e3
2  b90f87164b5f8c2cfa5c8572834dbe3f  6565aa9ce3178a5caf6171827af3a9ba
3  56bf83c4bb35763a51c2baab501b4c67  d3d1e91a157ea7f90548eef82f1955e3
4  4b339f9567d060bcea4f5136b9f5949e  d3d1e91a157ea7f90548eef82f1955e3

              won_date business_segment      lead_type lead_behaviour_profile  \
0  2018-02-26 19:58:54              pet  online_medium                    cat
1  2018-05-08 20:17:59  car_accessories       industry                  eagle
2  2018-06-05 17:27:23  home_appliances     online_big                    cat
3  2018-01-17 13:51:03       food_drink   online_small                    NaN
4  2018-07-03 20:17:45  home_appliances       industry                   wolf

  has_company has_gtin average_stock business_type  \
0         NaN      NaN           NaN      reseller
1         NaN      NaN           NaN      reseller
2         NaN      NaN           NaN      reseller
3         NaN      NaN           NaN      reseller
4         NaN      NaN           NaN  manufacturer

   declared_product_catalog_size  declared_monthly_revenue
0                            NaN                       0.0
1                            NaN                       0.0
2                            NaN                       0.0
3                            NaN                       0.0
4                            NaN                       0.0

### Marketing Qualified Leads (MQL) - Key Observations

* The dataset contains 8,000 marketing-qualified leads and 4 columns.
* mql_id appears to uniquely identify each lead.
* No duplicate records were found.
* Only 60 records have missing values in the origin column, representing less than 1% of the dataset.
* The dataset captures lead acquisition information, including first contact date, landing page, and acquisition source.
* Overall data quality is high and suitable for marketing funnel analysis.

### Closed Deals - Key Observations

* The dataset contains 842 successfully converted leads and 14 columns.
* mql_id can be used to link converted leads back to the marketing-qualified leads dataset.
* No duplicate records were detected.
* Several seller profiling fields contain substantial missing values, including company information, GTIN availability, stock levels, and product catalog size.
* Business segment, lead type, and business type are largely populated and remain useful for segmentation analysis.
* Despite missing seller attributes, the dataset is suitable for conversion, sales funnel, and lead quality analysis.

In [63]:
print("MQL Unique IDs:", mql['mql_id'].nunique())
print("Closed Deal Unique IDs:", closed_deals['mql_id'].nunique())

print(
    "Conversion Rate:",
    round(
        closed_deals['mql_id'].nunique() /
        mql['mql_id'].nunique() * 100,
        2
    ),
    "%"
)

MQL Unique IDs: 8000
Closed Deal Unique IDs: 842
Conversion Rate: 10.53 %

### Marketing Funnel Insights

* The Marketing Qualified Leads (MQL) dataset contains 8,000 leads generated through various acquisition channels.
* The Closed Deals dataset contains 842 successfully converted leads.
* Based on the available data, the lead-to-deal conversion rate is approximately 10.53%.
* This indicates that roughly 1 out of every 10 qualified leads ultimately became a seller on the platform.
* The datasets can be linked using mql_id, enabling future analysis of lead sources, sales performance, and conversion effectiveness.


### Marketing Funnel Summary

* The marketing dataset introduces a separate lead acquisition and conversion process that is independent from the marketplace transaction data.
* Out of 8,000 marketing-qualified leads, only 842 resulted in closed deals.
* This suggests an approximate lead-to-deal conversion rate of 10.5%.
* The datasets can be linked through mql_id to analyze lead sources, conversion performance, and sales effectiveness.
* These tables enable future marketing and sales funnel analytics beyond standard e-commerce reporting.